"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-06-09 19:33:14.177613

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foundry_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('linear_issue_id', sa.String(length=128), nullable=False),
    sa.Column('linear_issue_key', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('ANALYSING', 'NEEDS_CLARIFICATION', 'PLAN_READY', 'WAITING_APPROVAL', 'APPROVED', 'AGENT_RUNNING', 'PR_OPEN', 'REVIEW_REQUIRED', 'COMPLETE', 'BLOCKED', 'EXECUTION_FAILED', 'REJECTED', name='runstatus'), nullable=False),
    sa.Column('trigger_type', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('current_step', sa.String(length=64), nullable=True),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'BLOCKED', name='overallrisk'), nullable=True),
    sa.Column('agent_mode', sa.Enum('ANALYSIS_ONLY', 'DRAFT_PR', 'HUMAN_ONLY', name='agentmode'), nullable=True),
    sa.Column('approved_by', sa.String(length=128), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foundry_runs_linear_issue_id'), 'foundry_runs', ['linear_issue_id'], unique=False)
    op.create_index(op.f('ix_foundry_runs_linear_issue_key'), 'foundry_runs', ['linear_issue_key'], unique=False)
    op.create_table('foundry_agent_jobs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('provider_job_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED', name='agentjobstatus'), nullable=False),
    sa.Column('repo', sa.String(length=128), nullable=True),
    sa.Column('branch', sa.String(length=255), nullable=True),
    sa.Column('pr_url', sa.String(length=512), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['foundry_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foundry_agent_jobs_run_id'), 'foundry_agent_jobs', ['run_id'], unique=False)
    op.create_table('foundry_artifacts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('artifact_type', sa.Enum('TICKET_SNAPSHOT', 'TICKET_ANALYSIS', 'CONTEXT_BUNDLE', 'RISK_ASSESSMENT', 'DELIVERY_PLAN', 'APPROVAL_RECORD', 'AGENT_JOB', 'PR_STATE', 'FINAL_SUMMARY', name='artifacttype'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content_json', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['foundry_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_artifact_run_type', 'foundry_artifacts', ['run_id', 'artifact_type'], unique=False)
    op.create_index(op.f('ix_foundry_artifacts_content_hash'), 'foundry_artifacts', ['content_hash'], unique=False)
    op.create_index(op.f('ix_foundry_artifacts_run_id'), 'foundry_artifacts', ['run_id'], unique=False)
    op.create_table('foundry_audit_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('RUN_STARTED', 'TICKET_FETCHED', 'ANALYSIS_COMPLETED', 'CONTEXT_COMPLETED', 'POLICY_EVALUATED', 'APPROVAL_REQUESTED', 'APPROVAL_GRANTED', 'APPROVAL_REJECTED', 'AGENT_STARTED', 'AGENT_FAILED', 'AGENT_REMEDIATION_REQUESTED', 'PR_OPENED', 'PR_UPDATED', 'RISK_ESCALATED', 'CI_FAILED', 'REVIEW_COMPLETED', 'RUN_COMPLETED', 'RUN_BLOCKED', name='auditeventtype'), nullable=False),
    sa.Column('actor_type', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=True),
    sa.Column('input_hash', sa.String(length=64), nullable=True),
    sa.Column('output_hash', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['foundry_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foundry_audit_events_run_id'), 'foundry_audit_events', ['run_id'], unique=False)
    op.create_table('foundry_policy_decisions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('policy_name', sa.String(length=128), nullable=False),
    sa.Column('input_json', sa.Text(), nullable=False),
    sa.Column('decision_json', sa.Text(), nullable=False),
    sa.Column('allowed', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['foundry_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foundry_policy_decisions_run_id'), 'foundry_policy_decisions', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_foundry_policy_decisions_run_id'), table_name='foundry_policy_decisions')
    op.drop_table('foundry_policy_decisions')
    op.drop_index(op.f('ix_foundry_audit_events_run_id'), table_name='foundry_audit_events')
    op.drop_table('foundry_audit_events')
    op.drop_index(op.f('ix_foundry_artifacts_run_id'), table_name='foundry_artifacts')
    op.drop_index(op.f('ix_foundry_artifacts_content_hash'), table_name='foundry_artifacts')
    op.drop_index('idx_artifact_run_type', table_name='foundry_artifacts')
    op.drop_table('foundry_artifacts')
    op.drop_index(op.f('ix_foundry_agent_jobs_run_id'), table_name='foundry_agent_jobs')
    op.drop_table('foundry_agent_jobs')
    op.drop_index(op.f('ix_foundry_runs_linear_issue_key'), table_name='foundry_runs')
    op.drop_index(op.f('ix_foundry_runs_linear_issue_id'), table_name='foundry_runs')
    op.drop_table('foundry_runs')
    # PostgreSQL ENUM types survive table drops; drop them so downgrade/upgrade
    # round-trips work in CI (alembic downgrade base && alembic upgrade head).
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        for enum_name in (
            "auditeventtype",
            "artifacttype",
            "agentjobstatus",
            "agentmode",
            "overallrisk",
            "runstatus",
        ):
            op.execute(f"DROP TYPE IF EXISTS {enum_name}")
    # ### end Alembic commands ###
