"""agent job cost

Revision ID: 0002
Revises: 0001
Create Date: 2026-06-09 19:37:12.894779

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foundry_agent_jobs', sa.Column('cost_usd', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('foundry_agent_jobs', 'cost_usd')
    # ### end Alembic commands ###
